### PR TITLE
Add Github testing actions

### PR DESCRIPTION
**Pull request by wyatt**

### CODE REVIEW

**Comment by boon-cpu** [comment]
LGTM 👍🏻 🪨

**Comment by ctrl-cheeb-del** [comment]
LGTM :rocket:

**Review by boon-cpu — APPROVED** [review]

**Review by ctrl-cheeb-del — APPROVED** [review]

**Comment by hiett** [comment]
LGTM, thanks for merge, great PR

@wyatt - future PR, maybe you could set up the node_modules caching? It's really great for hugely improving CI times

https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows

You basically use a hash of the package.json file as the key, that way if any deps changes it re-downloads and then updates your cache. You can usually shave like up to 30s or so depending on dep count, and reduces the CI minutes charge for the account :)

**Comment by Copystrike** [comment]
What @hiett said.

**Comment by alii** [comment]
What @hiett said.

**Pull request merged**
